apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-wildcard-cert
  namespace: demo
spec:
  dnsNames:
  - 'www.bahkuyt.com'
  issuerRef:
    kind: ClusterIssuer
    name: democlusterissuer
  secretName: demo-wildcard-cert